create table patients (
  id int generated by default as identity primary key,
  name varchar(100),
  date_of_birth date
);

create table treatments (
  id int generated by default as identity primary key,
  type varchar(255),
  name varchar(100)
);

create table medical_histories(
  id int generated by default as identity primary key,
  admitted_at timestamp,
  patient_id int references patients(id),
  status varchar(200)
);

create table medical_histories_treatments(
  id int generated by default as identity primary key,
  treatment_id int references treatments(id),
  medical_history_id int references medical_histories(id)
);

create table invoices (
  id int generated by default as identity primary key,
  total_amount decimal,
  generated_at timestamp,
  payed_at timestamp,
  medical_history_id int references medical_histories(id)
);

create table invoice_items (
  id int generated by default as identity primary key,
  unit_price decimal,
  quantity int,
  total_price decimal,
  invoice_id int references invoices(id),
  treatment_id int references treatments(id)
);
