create table patients (
  id int generated by default as identity primary key,
  name varchar(100),
  date_of_birth date
);

create table treatments (
  id int generated by default as identity primary key,
  type varchar(255),
  name varchar(100)
);

create table medical_histories(
  id int generated by default as identity primary key,
  admitted_at timestamp,
  patient_id int references patients(id),
  status varchar(200)
);

create table medical_histories_treatments(
  id int generated by default as identity primary key,
  treatment_id int references treatments(id),
  medical_history_id int references medical_histories(id)
);
