/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id int generated by default as identity,
    name varchar(100) not null,
    date_of_birth date,
    weight_kg float,
    neutered boolean,
    escape_attemps int default 0
);
